version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: fedibenmansour/tp-ski:1.0.0
    container_name: tp-ski-app
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/db"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "pass"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - mysqldb

volumes:
  db_data:
